### ISSUE TITLE
Set up poetry

### ISSUE THREAD

**Issue by SagaRut** [REMLA24-Team-5/Model-Training#1]
This is a pain to set up bc of tensorflow: https://github.com/tensorflow/tensorflow/issues/62899

**Comment by Timdnb** [comment]
I set it up on Linux and it all runs, so only MacOS would be left if we want to be sure it works everywhere. I did get the following error: 

W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
