### ISSUE TITLE
Create operation repo + do submission things

### ISSUE THREAD

**Issue by SagaRut** [REMLA24-Team-5/Model-Training#16]
1. Create a git tag in your respective repositories to mark the state that should be reviewed. Keep it simple, using
tags like a1 , a2 , ... is clear enough.
2. In your operation repository, create a brief document with all required information about your project. Most
importantly, the document must start with a short section that includes repository links to all relevant material.
Link to ✮tags instead of ✮commits (compare the two links!) to create stable links.
3. Please mention for an assignment which tasks can be reviewed, esp. if a subtask is not done or incomplete. An
assessor should not spend time trying to find something that does not exist.

**Comment by Timdnb** [comment]
I've updated the operations repo with our current state
