### ISSUE TITLE
Now when you run dvc repro it updates the test.txt.dvc etc files, should that happen??

### ISSUE THREAD

**Issue by SagaRut** [REMLA24-Team-5/Model-Training#20]

**Comment by Timdnb** [comment]
Im assuming that's just something with how dvc works

**Comment by Timdnb** [comment]
Ah wait, maybe we should remove them from .git (i.e. put in gitignore), because these files are tracked by dvc?

**Comment by blibliboe** [comment]
If you remove them it might not work anymore with dvc
