### ISSUE TITLE
When using dvc repro on python 3.11.9 I get the error ImportError: cannot import name 'formatargspec' from 'inspect'

### ISSUE THREAD

**Issue by blibliboe** [REMLA24-Team-5/Model-Training#24]
A quick google search let me to find that formatargspec is not supported by python >= 3.11 we should make our project compatible with python >= 3.11

**Comment by SagaRut** [comment]
Well Jurrian did ask if it would it be possible to switch to python 3.10 so he can use dslinter...but since that is quite old then maybe we should set up pylint as well, the assignment even said to try multiple linters.

**Comment by blibliboe** [comment]
Yeah, I know he asked, but it is not a pylinter problem. It also breaks on old branches where it did not break before. No idea why that is the case

**Comment by blibliboe** [comment]
Okay it seems like it is a problem with tensorflow. With manually pip uninstall and pip install tensorflow it worked again.
