### ISSUE TITLE
Store model in accessible location with public link

### ISSUE THREAD

**Issue by Timdnb** [REMLA24-Team-5/Model-Training#35]

**Comment by Timdnb** [comment]
for now this should be on google drive at https://drive.google.com/file/d/185n3q-K-l3eiFwiThouljU_j9rYDugIX

**Comment by SagaRut** [comment]
this should be done in the pipeline not with dvc

**Comment by Timdnb** [comment]
Looking at it now, I don't think this is really necessary since the rubric says

"The model that is served can be updated without creating a new image, i.e., it is either downloaded on-start or mounted."

This is possible, and there is nothing about the method in which the model is updated, it is more about how it is included. So imo we can close this issue.

@SagaRut @Guthax
